### ISSUE TITLE
unit tests error with recurly 3.5.0

### ISSUE THREAD

**Issue by caleb15** [Captricity/mocurly#22]
Python version 3.6.9
Tests pass with recurly version 2.2.23 and 2.8.3
```
[9:21:12] caleb:mocurly git:(master) $ /usr/bin/python3 setup.py test                 
running test
running egg_info
writing mocurly.egg-info/PKG-INFO
writing dependency_links to mocurly.egg-info/dependency_links.txt
writing requirements to mocurly.egg-info/requires.txt
writing top-level names to mocurly.egg-info/top_level.txt
reading manifest file 'mocurly.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mocurly.egg-info/SOURCES.txt'
running build_ext
test_simple_transaction_creation (tests.test_transaction.TestTransaction) ... ERROR
test_transaction_failure (tests.test_transaction.TestTransaction) ... ERROR
test_transaction_list (tests.test_transaction.TestTransaction) ... ERROR
test_transaction_refund_amount_via_invoice (tests.test_transaction.TestTransaction) ... ERROR
test_transaction_refund_deprecation (tests.test_transaction.TestTransaction)
Tests that the old transaction refund interface no longer exists in mocurly. ... ERROR
test_transaction_refund_via_invoice (tests.test_transaction.TestTransaction) ... ERROR
test_transaction_void_via_invoice (tests.test_transaction.TestTransaction)
Uses the invoice refund system to void a transaction. ... ERROR
test_coupon_redemption_direct_discount (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_coupon_redemption_percent_discount (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_plan_deletion (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_simple_plan_add_on_creation (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_simple_plan_creation (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_simple_subscription_creation (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_subscription_cancel_reactivate (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_subscription_filtering (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_subscription_termination_full_refund (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_subscription_termination_partial_refund (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_subscriptions_with_addons (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_trial_override_subscription_creation (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_trial_subscription_creation (tests.test_subscriptions.TestSubscriptions) ... ERROR
test_account_creation_with_address (tests.test_account.TestAccount) ... ERROR
test_account_creation_with_billing_info (tests.test_account.TestAccount) ... ERROR
test_address_get_account (tests.test_account.TestAccount) ... ERROR
test_billing_info_get_account (tests.test_account.TestAccount) ... ERROR
test_close (tests.test_account.TestAccount) ... ERROR
test_delete_billing_info (tests.test_account.TestAccount) ... ERROR
test_invoice_list (tests.test_account.TestAccount) ... ERROR
test_list_account (tests.test_account.TestAccount) ... ERROR
test_no_account_retrieve (tests.test_account.TestAccount) ... ERROR
test_simple_account_creation (tests.test_account.TestAccount) ... ERROR
test_simple_account_update_billing_info (tests.test_account.TestAccount) ... ERROR
test_simple_get_account (tests.test_account.TestAccount) ... ERROR
test_update_account_with_billing_info (tests.test_account.TestAccount) ... ERROR
test_update_creditcard_billing_info (tests.test_account.TestAccount) ... ERROR
test_update_paypal_billing_info (tests.test_account.TestAccount) ... ERROR
test_context_manager (tests.test_core.TestCore) ... ERROR
test_decorate_class_method (tests.test_core.TestCore) ... ERROR
test_decorator (tests.test_core.TestCore) ... ERROR
test_exceptions (tests.test_core.TestCore)
Tests that exception objects do the right thing. ... ok
test_normal (tests.test_core.TestCore) ... ERROR
test_selective_timeout (tests.test_core.TestCore) ... ERROR
test_timeout (tests.test_core.TestCore) ... ERROR
test_timeout_successful_post (tests.test_core.TestCore) ... ERROR
test_url_encoding_handling (tests.test_core.TestCore)
Tests that mocurly correctly routes urlencoded pks ... ERROR
test_coupon_redemption (tests.test_coupons.TestCoupons) ... ERROR
test_simple_coupon_creation (tests.test_coupons.TestCoupons) ... ERROR

======================================================================
ERROR: test_simple_transaction_creation (tests.test_transaction.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_failure (tests.test_transaction.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_list (tests.test_transaction.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_refund_amount_via_invoice (tests.test_transaction.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_refund_deprecation (tests.test_transaction.TestTransaction)
Tests that the old transaction refund interface no longer exists in mocurly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_refund_via_invoice (tests.test_transaction.TestTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_transaction_void_via_invoice (tests.test_transaction.TestTransaction)
Uses the invoice refund system to void a transaction.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_transaction.py", line 15, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_coupon_redemption_direct_discount (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_coupon_redemption_percent_discount (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_plan_deletion (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_plan_add_on_creation (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_plan_creation (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_subscription_creation (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_subscription_cancel_reactivate (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_subscription_filtering (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_subscription_termination_full_refund (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_subscription_termination_partial_refund (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_subscriptions_with_addons (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_trial_override_subscription_creation (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_trial_subscription_creation (tests.test_subscriptions.TestSubscriptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_subscriptions.py", line 18, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_account_creation_with_address (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_account_creation_with_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_address_get_account (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_billing_info_get_account (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_close (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_delete_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_invoice_list (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_list_account (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_no_account_retrieve (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_account_creation (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_account_update_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_get_account (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_update_account_with_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_update_creditcard_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_update_paypal_billing_info (tests.test_account.TestAccount)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_account.py", line 14, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_context_manager (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 41, in test_context_manager
    with mocurly.mocurly():
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 43, in __enter__
    self.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_decorate_class_method (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 38, in test_decorate_class_method
    Demo().foo()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 35, in __call__
    self.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_decorator (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 29, in test_decorator
    foo()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 35, in __call__
    self.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_normal (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 48, in test_normal
    mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_selective_timeout (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 93, in test_selective_timeout
    mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_timeout (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 56, in test_timeout
    mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_timeout_successful_post (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 114, in test_timeout_successful_post
    mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_url_encoding_handling (tests.test_core.TestCore)
Tests that mocurly correctly routes urlencoded pks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_core.py", line 156, in test_url_encoding_handling
    foo()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 35, in __call__
    self.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_coupon_redemption (tests.test_coupons.TestCoupons)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_coupons.py", line 13, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

======================================================================
ERROR: test_simple_coupon_creation (tests.test_coupons.TestCoupons)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/caleb/Documents/misc/mocurly/tests/test_coupons.py", line 13, in setUp
    self.mocurly_.start()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 64, in start
    self._register()
  File "/home/caleb/Documents/misc/mocurly/mocurly/core.py", line 154, in _register
    list_uri = recurly.base_uri() + endpoint.base_uri
AttributeError: module 'recurly' has no attribute 'base_uri'

----------------------------------------------------------------------
Ran 46 tests in 0.005s

FAILED (errors=45)
Test failed: <unittest.runner.TextTestResult run=46 errors=45 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=46 errors=45 failures=0>
```

**Comment by pgrzesik** [comment]
I experienced similar issue. The last working `recurly` version is `2.9.16`
